version: '3'
services:
  api:
    image: node-api
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:28017"
    networks:
      - backend

networks:
  backend:
    driver: bridge